### ISSUE TITLE
Not seeing login forbidden errors

### ISSUE THREAD

**Issue by queso** [meteor-useraccounts/core#279]
When I leave any field blank on the sign in page I see no 'Login Forbidden' error. Seems like a pretty big bug.

**Comment by splendido** [comment]
This is actually by *design*: see [these lines](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L151-155)

I now recall it was introduced because of [this issue](https://github.com/meteor/meteor/issues/2272) but I guess we can now get rid of that check and let the normal login flow being executed.

Tnx for the pointer Josh!

**Comment by splendido** [comment]
Done @queso!

Btw, you could have shooted a little less harder on [your post](http://joshowens.me/cucumber-js-and-meteor-the-why-and-how-of-it/): the bug was there, right, but only in case you left one of the two input fields empty.

In case of bad values the login error was correctly shown!!! ;-)
