### ISSUE TITLE
unable to use intl-tel-input jquery plugin for custom input field

### ISSUE THREAD

**Issue by Hareramrai** [meteor-useraccounts/core#296]
Hi,

I want to use https://github.com/Bluefieldscom/intl-tel-input for phone number field during register.

But I am not sure where add below code.

 // $("#at-field-cellPhone").intlTelInput({
  //     defaultCountry: "auto",
  //     utilsScript: "libphonenumber/build/utils.js" // just for formatting/placeholders etc
  // });

Please help me on this.

**Comment by Hareramrai** [comment]
I have written the below code.

````
Template.fullPageAtForm.rendered = function(){
  console.log($('#at-field-cellPhone').length)
  $("#at-field-cellPhone").intlTelInput({
      defaultCountry: "auto",
      utilsScript: "libphonenumber/build/utils.js" // just for formatting/placeholders etc
  });
}
````
Its working for first time but not working when we came back after visiting the some other page.

**Comment by splendido** [comment]
Lets try to move it to `Template.atPwdForm.rendered`!

Otherwise you can try to define your own template for the telephone input: lets have a look a the examples [here](https://github.com/meteor-useraccounts/wiki/tree/master/customInputFields)
...in case, I'd like to get one more example about this ;-)
