### ISSUE TITLE
custom vaidation on a specific form route only?

### ISSUE THREAD

**Issue by Jehu** [meteor-useraccounts/core#338]
My Problem:
I check the email for already existing ones, like it is documented for "usernames" in the docs.
But, the validation should not take affect if the user want to use the resetPwd route.

How can i check for the current route?
Router.current().route.path() returns "/" all the time.

**Comment by splendido** [comment]
hello @Jehu!

Which code are you using for the validation?
If it's a server side method, IR might return "/" because there's not *current* route on the server...

I'd say you could use `AccountsTemplates.getState()` on the client conparing it against `changePwd` to choose whether to trigger the server-side method or not...
does this make sense?

**Comment by Jehu** [comment]
yeah! this make sense. Thank you!
