### ISSUE TITLE
show signin & signup at the same time

### ISSUE THREAD

**Issue by ShawnOceanHu** [meteor-useraccounts/core#345]
Hi guys, awesome work !

I tried to add a customized sign in/up UI that displays the sign in & sign up at the same page, but I found it really hard to do so, because the sign-in/up _fields are shared in the core library, so is it possible to separate them ? so that these functions can stay in the same page.

: )

**Comment by splendido** [comment]
As you already discovered, this is quite tricky to achieve at the moment.

Even if the purpose for `{{> atForm state='somestate'}}` is exactly this one, there are a number of other things which is difficult to deal with.

I'm playing with `useraccounts@2.0` and I'll try to keep your needs in mind:

* error messages should be set/shown per template instance instead of *globally*
* template's parameters might be used to hide some *module* (e.g. `{{> uaForm hide='link'}}`)

I'll let you know when I'll have some code pushed to github for you to test (at the moment I'm playing locally on my machine...)

**Comment by ShawnOceanHu** [comment]
This is really awesome, can't wait to see these new features : )

**Comment by splendido** [comment]
This is already possible with the current code on `v2.0` branch

**Comment by ShawnOceanHu** [comment]
Wow really awesome work, @splendido !

**Comment by splendido** [comment]
I'd better publish some alpha release so that people could start testing it out, but I'd like to put something more in before...
Lets see how it goes...
