### ISSUE TITLE
How to change the display location of an error message(bootstrap)?

### ISSUE THREAD

**Issue by riguk** [meteor-useraccounts/core#368]
When there is an error message, it will be displayed under the current input.
And when the error message show and disappear, it will make the inputs under the error temporarily move.
So I want the inputs fixed and I have two approaches.
1. Make the error message show above the title.
2. Make the error message show under the current input, but don't case the inputs below move by increasing margin-bottom?

Which one will be easy and how can I do that? Or could you please give me other advise?
Thank you.

**Comment by splendido** [comment]
If you wish to play with some CSS rule, [this](https://github.com/meteor-useraccounts/bootstrap/blob/master/lib/at_input.html#L14) is the line showing/hiding the error message.

You might want to change the template used providing a custom one: see #212 

Another option is to set `negativeValidation` to false so to get error messages all inside the form error box rather than below single inputs.
See [Form Fields Configuration](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#form-fields-configuration) for field by field settings or [options](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#options)  for global [Configuration API](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#configuration-api)

**Comment by splendido** [comment]
any updates on this?
