### ISSUE TITLE
Unable to require username AND email for new accounts

### ISSUE THREAD

**Issue by cpalanzo** [meteor-useraccounts/core#412]
I saw an earlier comment that solved this problem #58 - that requires adding fields manually.
Is this still the preferred solution? Or is there a simple option setting for this now?
Great package! Thanks.

**Comment by splendido** [comment]
Have you had a look at [this](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#login-with-username-or-email)?

**Comment by derwaldgeist** [comment]
I also tried to setup AccountsTemplates to show both the username *and* the email. But even if I do it like described [here](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#login-with-username-or-email), I still get a combined username and password field. But I want to have both fields separately, since both are needed for my application.
