### ISSUE TITLE
Pressing back on social login on mobile disables the form

### ISSUE THREAD

**Issue by bozkan** [meteor-useraccounts/core#417]
It is completely OK on browser, but when I want to login with social accounts and press back before logging in on the fb/twitter login page, all the social buttons are disabled. 

I also tried removing 'disabled' class when rendering. It is ok in CSS, but buttons are not still functional. Could you recommend me any solution? Thanks.

**Comment by challett** [comment]
+1 on this issue

**Comment by splendido** [comment]
Is this still an issue with the new [useraccounts:iron-routing](https://github.com/meteor-useraccounts/iron-routing) package?

On all UA configured routes there's an `onStop` hook calling `AccountsTemplates.clearState()` which in turn should remove the disabled status from the form: see [here](https://github.com/meteor-useraccounts/iron-routing/blob/f67fd8c65b12751124855a67cfb8d829ddd1226c/lib/client.js#L23)
And [this](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_social.js#L2-L13) is the helper used to choose whether to put in the `disabled` class or not...

**Comment by challett** [comment]
Seems to still be happening in my environment after adding the iron-routing package

**Comment by splendido** [comment]
This is probably due to the `Accounts.setDisabled(true);` [called on social button click](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_social.js#L70) and not counteracted by `Accounts.setDisabled(false);` which is [supposed to be called on login completed/failed](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_social.js#L92) even if `Accounts.LoginCancelledError` is intercepted.

If this is still an issue I suggest to call `Accounts.setDisabled(false);` before rendering the `atForm` template in case you're not using any routing package.
