### ISSUE TITLE
Question signup with signup code

### ISSUE THREAD

**Issue by almogdesign** [meteor-useraccounts/core#435]
I wanted to know if there any examples to have a signup use signup code or has anyone else done this?

**Comment by splendido** [comment]
There's something about it [here](https://github.com/meteor-useraccounts/core/issues/95#issuecomment-61338257) but simply to pick up a signup code from a URL.
There's also something [here](https://github.com/meteor-useraccounts/core/issues/228) about using fields' asynchronous validation to verify codes... [this comment](https://github.com/meteor-useraccounts/core/issues/228#issuecomment-70304388) seems the more close to your needs.
Please consider it's an old post...

But there's nothing about DB management, since it won't fit everyone's use case! ;-)
