### ISSUE TITLE
Question: any way to sign-out without an atNavButton ?

### ISSUE THREAD

**Issue by thetechnaddict** [meteor-useraccounts/core#452]
How does a user sign out?

**Comment by challett** [comment]
You can just call Meteor.logout() or AccountsTemplates.logout() if you want to use the onLogout callback.  Call these on an event such as a button press and your user will be logged out

**Comment by Alveoli** [comment]
On a related note - any way to customise {{>atNavButton}} so that it DOESN'T have a sign-out incarnation? I don't want to encourage that kind of behaviour ;)

**Comment by splendido** [comment]
@Alveoli : I've never been too happy about having an `atNavButton` because it will hardly suits everyones' needs...
If you look at the code [here](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_nav_button.js) and [here](https://github.com/meteor-useraccounts/bootstrap/blob/master/lib/at_nav_button.html) (for example...) you'll appreciate it's very easy to roll your one ;-)

**Comment by splendido** [comment]
thanks @challett for answering the question!

**Comment by Alveoli** [comment]
Thanks all!
