### ISSUE TITLE
[question] Show reCaptcha after several failed attempt?

### ISSUE THREAD

**Issue by speciose** [meteor-useraccounts/core#486]
Is there any option that will set recaptcha to appear only after several failed login attempts?

**Comment by splendido** [comment]
no, not at the moment...
and I don't think it would be an easy add.

To get to this you should first track the number of failed login attempts on the server side, not actually for a particular user but probably for a particular client (since if you're failing the login it might not be for one specific username in general).
The you should throw different errors based on when the reCaptcha is to be shown and intercept them on the cient side...

Would be a nice exercise ;-)
