### ISSUE TITLE
using t9n in user-account core

### ISSUE THREAD

**Issue by Philip-Nunoo** [meteor-useraccounts/core#487]
I'm using the t9n package to translate my page to french 
have added the package __softwarerero:accounts-t9n__

called __T9n.setLanguage("pt")__ within a lib folder in the project root directory.

But still can't get the translation  for these error messages
![image](https://cloud.githubusercontent.com/assets/1866811/8980708/34058de2-36a2-11e5-95d6-d452d754536f.png)

**Comment by splendido** [comment]
The problem is the [pt file](https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/pt.coffee) is missing the key for required field.

You can set it up with
```javascript
T9n.map('py', {
  'Required Field': 'xyz'
});
```

see also [this comment](https://github.com/meteor-useraccounts/core/issues/200#issuecomment-70505397)

..or you could make a PR on `accounts-t9n` to include the new key.

Let me know whether the self-definition works
