### ISSUE TITLE
Way to only show SignUpLink on specific routes (or hide on specific routes)

### ISSUE THREAD

**Issue by soitech** [meteor-useraccounts/core#508]
I have users with multiple roles. Only one user role do I want to be able to use signUp. In fact, any new user created through signUp goes to that role only. The various roles correspond to different login portals, so I'd like the "Don't Have an Account? Register" link to only appear in one specific login area. 

I'm using iron-router and Router.plugin('ensureSignedIn'... to make sure users are signed in throughout the whole site except the home page and various 'at' templates. Is there something I can add to the AccountsTemplates.configureRoute('signIn',.... to only show the signUp link if the current path/route is something specific?

**Comment by splendido** [comment]
I'm not going into the policy you're implementing to have different *roles* assigned based on the login/signup url but be aware about possible security flaws...
Be sure to not allow a user to gain *admin* privileges only because she signed up from a different url!

This said, [this helper](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_form.js#L54-L59) is the one responsible to tell whether the link is to be shown or not.
Feel free to override it to suite your needs:

```javascript
AccountsTemplates.atFormHelpers.showSignUpLink = myShowSignUpLink
```

`myShowSignUpLink` should consider the current route from IR to decide what to return...

**Comment by soitech** [comment]
Thanks, that should lead me in the right direction. 

I didn't explain clearly. I'm not assigning different roles based on login/signup. I just have different places for folks to login based on their role. 

Basically, there are Students, Teachers, and then a couple of types of management and admin users. 
The students and teachers have separate "portals" where they enter the site. Any new user created through atSignUp will automatically be a Student account... and have the least amount of access privileges. 

So, I don't want the register link to appear on the Teacher login page, as Teacher accounts are created internally by an admin, and if a Teacher tries to register through the link rather than contacting an admin to create their account... they'll end up as a student and be taken to the student area of the site when they login. 

Having roles assigned based on where a user registered would definitely create security concerns!
Thanks again.
