### ISSUE TITLE
AccountsTemplates.addField: store user field on document other than profile

### ISSUE THREAD

**Issue by juliomac** [meteor-useraccounts/core#520]
Currently when adding a field with ```AccountsTemplates.addField``` it stores the values under Meteor.users.profile.

Is there a way to define other subdocument instead of profile? The goal is to have more organization and store other sensitive information, like one for CreditCardInfo.Number.

Is it possible ?

**Comment by splendido** [comment]
You can use the [Accounts.onCreateUser](https://docs.meteor.com/#/full/accounts_oncreateuser) callback to modify the user object the way you'd like to before it enters the users collection.

I think this is the only reasonable way to do it, trying to change the behaviour of UA wouldn't fit everyone's needs in any case.

Let me know if you need more help.
Tnx

**Comment by juliomac** [comment]
Nice tip! I will try it out and let you know how it comes out.

**Comment by jaakkopiipponen** [comment]
How did it turn out @juliomac ?

And @splendido , I'd appreciate any pointers you might have! I'm trying to integrate alanning: roles with addField, but since their method requires a userId, I won't be able to use onCreateUser since the userId hasn't been created yet. 

I got the roles working with a hardcoded value with after.insert collection hook, but I was wondering how can I tie that to the addField value without touching the user.profile?

**Comment by splendido** [comment]
@jaakkopiipponen follow #536 to get the problem with `alanning:roles` sorted out

**Comment by jaakkopiipponen** [comment]
Thanks @splendido !
