### ISSUE TITLE
Is there a way to create a new AT.prototype.STATES

### ISSUE THREAD

**Issue by rufusthecat** [meteor-useraccounts/core#527]
I would like to add another state like (update account) where a user once logged in could go to his profile page and update fields like email, first name, last name, company, tel etc... 
Once I have a new STATE then would like to customize the fields in it as to remove a few of them that I have created in the createAccount template.

It would be separate from the update password template as they are two seperate actions

Haven't been able to find an example of this

Thanks

**Comment by splendido** [comment]
That would be quite complicated at the moment since it'd require to rewrite most of the helpers used to show/hide input fileds and sub-templates.

But if you're using [aldeed:simple-schema](https://atmospherejs.com/aldeed/simple-schema) and [aldeed:autoform](https://atmospherejs.com/aldeed/autoform) it should be easy enough to create a profile update page like the one you're describing.
