### ISSUE TITLE
Links in atForm template are reversed/incorrect

### ISSUE THREAD

**Issue by polished85** [meteor-useraccounts/core#539]
The sign in and sign up templates have a link to the other page. Example: on the 'sign up' template, there is a link that says 'If you already have an account sign in'. This link should take me to the sign in view, but it instead it links me to the 'sign up' view, which is where I already am. The reverse is true for the sign in page.
![atform-issue](https://cloud.githubusercontent.com/assets/4803749/9984128/18a5b7d6-5fc7-11e5-8cf5-26aa1158dbb4.jpg)

**Comment by PhilippSpo** [comment]
I just tried the boilerplates for flow-router and iron-router and this works just fine.
Looking at your screenshot of the elements, the link that should point to singIn actually points to `#`, which is why you stay on the same (sing-up) route when you click it.
Since the `signInLink` is retrieved from your route configuration I guess that you either forgot to configure just that or that you are not using either the flow-routing or iron-routing package?

**Comment by polished85** [comment]
Hey, thanks for the reply. I am using flow router and did not configure the 'signInLink'. Was not aware I had to configure this, but it makes perfect sense. Thank you for looking into this.
