### ISSUE TITLE
AtForm displays enrollment form, when it shouldn't

### ISSUE THREAD

**Issue by maksimkurb** [meteor-useraccounts/core#591]
I have an >atForm tag on users profile page, because I want to use social buttons. But if I click on enrollement link and fill my credentials, >atForm magically don't rerendered. Seems enrollment form is not fully reactive.

How to reproduce:

1) send an enrollment email to yourself

![2015-11-21 15 02 37](https://cloud.githubusercontent.com/assets/1351924/11318444/15323436-9063-11e5-92d9-6551640c04e1.png)

2) fill an enrollment form 

![2015-11-21 15 03 06](https://cloud.githubusercontent.com/assets/1351924/11318445/266cadf8-9063-11e5-8884-d503bdef5d2f.png)

3) go to page with >atForm tag and get confused by seeing this enrollment form again (instead of social buttons)

![2015-11-21 15 04 30](https://cloud.githubusercontent.com/assets/1351924/11318452/5c4d4770-9063-11e5-9552-793f0c58084c.png)

If you reload page, problem will disappear

**Comment by maksimkurb** [comment]
I can add, that ```AccountsTemplates.getState()``` returns ```"enrollAccount"```
It can be fixed by using ```>atForm(state="signIn")``` to force state, but this is workaround

**Comment by splendido** [comment]
@maksimkurb the _problem_ is that the `atForm` template is usually displayed with the lates state set.
Hence after you route through an `enrollAccount` page the form is left with the current state set to `enrollAccount`.
This is actually the normal expected behaviour!

I'd say you have two alternatives:
1. as you already pointed out, use ```{{> atFrom state="signIn"}}``` on your user profile page to force the correct state (this is not a workaround as long as you don't want the user to chage form state from the profile page...).
2. exploit some `onRendered` hook from within the profile page to set the `signIn` state to the form with ```AccountsTemplates.setState('signIn');```.
